version: '3.8'

services:
  backend:
    build: ./backend
    command: sh ./backend/entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ${POSTGRES_DB_VOLUME}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
