# Generated by Django 4.1.7 on 2023-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclassifier',
            name='output_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
